// Oracle PL/SQL topic tree.

/** @type {import('@/lib/content').ConceptNode[]} */
const topics = [
  {
    id: 'plsql-block-structure',
    title: 'Block Structure',
    level: 1,
    slug: 'block-structure',
    concepts: [],
    children: [
      {
        id: 'plsql-anonymous-blocks',
        title: 'Anonymous Blocks',
        level: 2,
        slug: 'anonymous-blocks',
        concepts: [
          {
            id: 'plsql-block-basic',
            code: "DECLARE\n  v_name VARCHAR2(100) := 'World';\n  v_count NUMBER;\nBEGIN\n  SELECT COUNT(*) INTO v_count FROM employees;\n  DBMS_OUTPUT.PUT_LINE('Hello ' || v_name || ', count: ' || v_count);\nEXCEPTION\n  WHEN NO_DATA_FOUND THEN\n    DBMS_OUTPUT.PUT_LINE('No data');\nEND;\n/",
            note: "A PL/SQL block has three parts: DECLARE (optional), BEGIN...END (executable), and EXCEPTION (optional). Anonymous blocks run immediately and are not stored.",
            explanation: {
              heading: 'The PL-SQL block anatomy',
              intro: 'Every PL-SQL program is built from blocks, and understanding the three sections is the foundation for procedures, functions, and triggers.',
              points: [
                { term: 'Declaration section', detail: 'The optional DECLARE part defines variables, constants, cursors, and types that exist only within the block.' },
                { term: 'Executable section', detail: 'The mandatory BEGIN...END part holds the procedural logic and SQL statements that actually run.' },
                { term: 'Exception section', detail: 'The optional EXCEPTION part traps runtime errors so the block can recover gracefully instead of failing outright.' },
                { term: 'Anonymous versus stored', detail: 'An anonymous block is compiled and executed on the fly and is not saved in the database, unlike named procedures or functions.' },
                { term: 'Trailing slash', detail: 'In tools like SQL Star Plus a single slash on its own line tells the client to submit and run the block.' },
              ],
            },
            example: "BEGIN DBMS_OUTPUT.PUT_LINE('hi'); END;\n/",
          },
          {
            id: 'plsql-nested-blocks',
            code: "BEGIN\n  DBMS_OUTPUT.PUT_LINE('outer');\n  DECLARE\n    v_x NUMBER := 1;\n  BEGIN\n    DBMS_OUTPUT.PUT_LINE('inner ' || v_x);\n  END;\nEND;\n/",
            note: "Blocks can nest inside the executable or exception section. Inner blocks create their own scope and can have their own EXCEPTION handlers, allowing localized error recovery.",
            explanation: {
              heading: 'Nesting blocks for scope',
              intro: 'PL-SQL lets you place a complete block inside another, which is useful for isolating variables and handling errors close to where they happen.',
              points: [
                { term: 'Local scope', detail: 'Variables declared in an inner block are visible only there, so they do not clash with names in the enclosing block.' },
                { term: 'Localized handlers', detail: 'An inner EXCEPTION section catches errors from just that block, letting the outer block continue after recovery.' },
                { term: 'Re-raising upward', detail: 'If an inner handler cannot cope it can RAISE the error again so an outer handler gets a chance to respond.' },
                { term: 'Name visibility', detail: 'Inner blocks can read outer variables, and block labels can qualify names when an inner declaration hides an outer one.' },
                { term: 'Readability tradeoff', detail: 'Deep nesting hurts clarity, so factor complex logic into named procedures instead of stacking many inner blocks.' },
              ],
            },
            example: "BEGIN BEGIN NULL; END; END;\n/",
          },
        ],
        children: [],
      },
    ],
  },
  {
    id: 'plsql-variables',
    title: 'Variables and Types',
    level: 1,
    slug: 'variables',
    concepts: [],
    children: [
      {
        id: 'plsql-declaring-variables',
        title: 'Declaring Variables',
        level: 2,
        slug: 'declaring',
        concepts: [
          {
            id: 'plsql-var-basic',
            code: "DECLARE\n  v_total   NUMBER(10,2) := 0;\n  v_name    VARCHAR2(50);\n  c_tax     CONSTANT NUMBER := 0.08;\n  v_active  BOOLEAN := TRUE;\nBEGIN\n  v_total := 100 * (1 + c_tax);\nEND;\n/",
            note: "Variables are declared in the DECLARE section with a type and optional initializer (:=). CONSTANT marks read-only values. BOOLEAN exists in PL/SQL but not in SQL columns.",
            explanation: {
              heading: 'Declaring and typing variables',
              intro: 'PL-SQL variables must be declared before use, and Oracle offers precise numeric, character, and Boolean types tailored to procedural code.',
              points: [
                { term: 'Assignment operator', detail: 'The colon-equals operator both initializes a variable in its declaration and assigns to it later in the executable section.' },
                { term: 'CONSTANT keyword', detail: 'A CONSTANT must be given a value when declared and can never be changed afterward, which protects fixed values like tax rates.' },
                { term: 'Precision and scale', detail: 'A NUMBER can carry precision and scale, so NUMBER(10,2) stores up to ten digits with two after the decimal point.' },
                { term: 'BOOLEAN is PL-SQL only', detail: 'The BOOLEAN type holds TRUE, FALSE, or NULL in code but cannot be used as a table column type in SQL.' },
                { term: 'VARCHAR2 for text', detail: 'Oracle favors VARCHAR2 over CHAR for variable-length strings, sizing it in bytes or characters as declared.' },
              ],
            },
            example: "v_pi CONSTANT NUMBER := 3.14159;",
          },
          {
            id: 'plsql-not-null-default',
            code: "DECLARE\n  v_status VARCHAR2(10) NOT NULL := 'new';\n  v_qty    NUMBER DEFAULT 0;\nBEGIN\n  v_qty := v_qty + 1;\nEND;\n/",
            note: "A NOT NULL variable must be initialized and can never be assigned NULL. DEFAULT is a synonym for := in a declaration. These guards catch missing-value bugs early.",
            explanation: {
              heading: 'NOT NULL and DEFAULT guards',
              intro: 'Oracle lets you constrain variables at declaration time so that invalid or missing values are caught during compilation or at runtime.',
              points: [
                { term: 'Mandatory initializer', detail: 'A variable declared NOT NULL must be given a starting value in the same declaration or the block will not compile.' },
                { term: 'Runtime protection', detail: 'Any later attempt to assign NULL to a NOT NULL variable raises the VALUE_ERROR exception.' },
                { term: 'DEFAULT keyword', detail: 'Writing DEFAULT is exactly equivalent to using the colon-equals operator to supply an initial value.' },
                { term: 'Intent signaling', detail: 'Combining NOT NULL with DEFAULT documents that a variable should always hold a real value from the start.' },
                { term: 'Early bug detection', detail: 'These constraints surface missing-value mistakes near the declaration rather than deep inside later logic.' },
              ],
            },
            example: "v_flag BOOLEAN NOT NULL DEFAULT FALSE;",
          },
        ],
        children: [],
      },
    ],
  },
  {
    id: 'plsql-anchored-types',
    title: '%TYPE and %ROWTYPE',
    level: 1,
    slug: 'anchored-types',
    concepts: [],
    children: [
      {
        id: 'plsql-anchored-usage',
        title: 'Anchored Declarations',
        level: 2,
        slug: 'anchored-usage',
        concepts: [
          {
            id: 'plsql-type-basic',
            code: "DECLARE\n  v_sal   employees.salary%TYPE;\n  v_emp   employees%ROWTYPE;\nBEGIN\n  SELECT * INTO v_emp FROM employees WHERE employee_id = 100;\n  v_sal := v_emp.salary;\nEND;\n/",
            note: "%TYPE anchors a variable to a column's type; %ROWTYPE anchors a record to a whole table row. Declarations stay in sync automatically if the table changes.",
            explanation: {
              heading: 'Anchoring to the data model',
              intro: 'Anchored declarations tie your PL-SQL variables to database columns and rows so code adapts automatically when the schema evolves.',
              points: [
                { term: 'Percent TYPE', detail: 'Attaching percent-TYPE to a column reference gives the variable the exact datatype and size of that column.' },
                { term: 'Percent ROWTYPE', detail: 'Attaching percent-ROWTYPE to a table gives a record whose fields mirror every column of that table in order.' },
                { term: 'Schema resilience', detail: 'If a column widens from VARCHAR2 fifty to VARCHAR2 one hundred, anchored variables pick up the change on recompile.' },
                { term: 'Self-documenting', detail: 'Anchored types make intent obvious because the code states which column or table the value comes from.' },
                { term: 'Field access', detail: 'A percent-ROWTYPE record exposes each column as a field reached with dot notation, such as record dot salary.' },
              ],
            },
            example: "v_id departments.department_id%TYPE;",
          },
          {
            id: 'plsql-cursor-rowtype',
            code: "DECLARE\n  CURSOR c IS SELECT first_name, salary FROM employees;\n  v_row c%ROWTYPE;\nBEGIN\n  OPEN c; FETCH c INTO v_row; CLOSE c;\n  DBMS_OUTPUT.PUT_LINE(v_row.first_name);\nEND;\n/",
            note: "%ROWTYPE also anchors to a cursor's projection, so the record has exactly the selected columns. This keeps fetch targets correct even when the cursor's SELECT list changes.",
            explanation: {
              heading: 'Cursor-anchored records',
              intro: 'You can anchor a record to a cursor rather than a table so its structure matches the exact columns the query selects.',
              points: [
                { term: 'Projection matching', detail: 'A cursor percent-ROWTYPE record has one field per selected expression, in the same order as the SELECT list.' },
                { term: 'Safe fetching', detail: 'Fetching into a cursor-anchored record guarantees the targets line up with the query so no mismatch error occurs.' },
                { term: 'Adapts to edits', detail: 'When the cursor SELECT list changes, the anchored record changes with it once the code is recompiled.' },
                { term: 'Alias-driven names', detail: 'Column aliases in the cursor become the field names, so give computed expressions clear aliases.' },
                { term: 'Cleaner than lists', detail: 'One record target is tidier than declaring and maintaining a separate variable for each selected column.' },
              ],
            },
            example: "v_rec some_cursor%ROWTYPE;",
          },
        ],
        children: [],
      },
    ],
  },
  {
    id: 'plsql-control-structures',
    title: 'Control Structures',
    level: 1,
    slug: 'control-structures',
    concepts: [],
    children: [
      {
        id: 'plsql-conditions-loops',
        title: 'Conditions and Loops',
        level: 2,
        slug: 'conditions-loops',
        concepts: [
          {
            id: 'plsql-if-case',
            code: "IF v_score >= 90 THEN\n  v_grade := 'A';\nELSIF v_score >= 80 THEN\n  v_grade := 'B';\nELSE\n  v_grade := 'C';\nEND IF;",
            note: "IF/ELSIF/ELSE branches on conditions; a CASE statement or expression handles multi-way selection more compactly.",
            explanation: {
              heading: 'Branching with IF and CASE',
              intro: 'PL-SQL offers both IF chains and CASE constructs to choose between alternatives, each suited to a different style of decision.',
              points: [
                { term: 'IF ELSIF ELSE', detail: 'An IF chain evaluates each condition in order and runs the first branch whose condition is TRUE.' },
                { term: 'CASE statement', detail: 'A CASE statement executes one of several branches and ends with END CASE, ideal for many discrete choices.' },
                { term: 'CASE expression', detail: 'A CASE expression returns a value that can be assigned to a variable or used inside a larger expression.' },
                { term: 'Searched versus simple', detail: 'Simple CASE compares one value to constants while searched CASE evaluates independent boolean conditions.' },
                { term: 'NULL handling', detail: 'A condition that evaluates to NULL is treated as not TRUE, so the branch is skipped just like a FALSE result.' },
              ],
            },
            example: "v_g := CASE WHEN v_score >= 90 THEN 'A' ELSE 'B' END;",
          },
          {
            id: 'plsql-loops',
            code: "FOR i IN 1..5 LOOP\n  DBMS_OUTPUT.PUT_LINE(i);\nEND LOOP;\n\nWHILE v_n > 0 LOOP\n  v_n := v_n - 1;\nEND LOOP;",
            note: "PL/SQL has basic LOOP (with EXIT), numeric FOR loops, and WHILE loops. Numeric FOR loops implicitly declare their counter and iterate a range.",
            explanation: {
              heading: 'The three loop forms',
              intro: 'PL-SQL provides three looping constructs so you can pick the one that best fits how the iteration count is determined.',
              points: [
                { term: 'Basic LOOP', detail: 'A plain LOOP repeats until an EXIT or EXIT WHEN statement inside it decides to stop, giving full manual control.' },
                { term: 'Numeric FOR loop', detail: 'A FOR loop iterates over a numeric range and automatically declares a counter that is read-only inside the loop.' },
                { term: 'WHILE loop', detail: 'A WHILE loop tests its condition before each pass and runs zero times if the condition starts out false.' },
                { term: 'Implicit counter', detail: 'The FOR loop counter exists only within the loop and does not need or allow a separate declaration.' },
                { term: 'Guaranteed one pass', detail: 'A basic LOOP always runs its body at least once because the exit test lives inside the body.' },
              ],
            },
            example: "LOOP EXIT WHEN v_done; END LOOP;",
          },
          {
            id: 'plsql-continue-reverse',
            code: "FOR i IN REVERSE 1..5 LOOP\n  CONTINUE WHEN MOD(i, 2) = 0;  -- skip even numbers\n  DBMS_OUTPUT.PUT_LINE(i);\nEND LOOP;",
            note: "REVERSE iterates a numeric FOR loop from high to low. CONTINUE (and CONTINUE WHEN) skips to the next iteration, the counterpart of EXIT for early continuation.",
            explanation: {
              heading: 'Controlling loop flow',
              intro: 'REVERSE and CONTINUE give finer control over how a loop steps through its range and which iterations do work.',
              points: [
                { term: 'REVERSE keyword', detail: 'Adding REVERSE to a numeric FOR loop counts down from the high bound to the low bound instead of up.' },
                { term: 'Bounds stay ordered', detail: 'Even with REVERSE the range is still written low then high, and Oracle walks it from the top downward.' },
                { term: 'CONTINUE statement', detail: 'CONTINUE abandons the current iteration and jumps straight to the next one without leaving the loop.' },
                { term: 'CONTINUE WHEN', detail: 'CONTINUE WHEN adds a condition so the skip happens only when that condition is TRUE, keeping code compact.' },
                { term: 'Introduced in 11g', detail: 'The CONTINUE statement arrived in Oracle Database 11g and complements EXIT for cleaner loop logic.' },
              ],
            },
            example: "CONTINUE WHEN v_skip;",
          },
        ],
        children: [],
      },
    ],
  },
  {
    id: 'plsql-cursors',
    title: 'Cursors',
    level: 1,
    slug: 'cursors',
    concepts: [],
    children: [
      {
        id: 'plsql-explicit-cursors',
        title: 'Explicit Cursors',
        level: 2,
        slug: 'explicit-cursors',
        concepts: [
          {
            id: 'plsql-cursor-explicit',
            code: "DECLARE\n  CURSOR emp_cur IS SELECT employee_id, first_name FROM employees WHERE department_id = 10;\n  v_emp emp_cur%ROWTYPE;\nBEGIN\n  OPEN emp_cur;\n  LOOP\n    FETCH emp_cur INTO v_emp;\n    EXIT WHEN emp_cur%NOTFOUND;\n    DBMS_OUTPUT.PUT_LINE(v_emp.first_name);\n  END LOOP;\n  CLOSE emp_cur;\nEND;\n/",
            note: "Explicit cursors give row-by-row control: OPEN, FETCH INTO, then CLOSE. Cursor attributes %FOUND, %NOTFOUND, and %ROWCOUNT track state.",
            explanation: {
              heading: 'The explicit cursor lifecycle',
              intro: 'Explicit cursors let you process a query result one row at a time with full control over each stage of the cursor.',
              points: [
                { term: 'OPEN', detail: 'Opening the cursor runs the query and positions the result set so the first row is ready to fetch.' },
                { term: 'FETCH INTO', detail: 'Each FETCH pulls the next row into target variables or a record, advancing the cursor by one row.' },
                { term: 'CLOSE', detail: 'Closing releases the cursor and its resources, and forgetting to close in a loop can leak open cursors.' },
                { term: 'Status attributes', detail: 'Percent-FOUND, percent-NOTFOUND, and percent-ROWCOUNT report whether the last fetch got a row and how many have been fetched.' },
                { term: 'Loop exit', detail: 'The idiom EXIT WHEN cursor percent-NOTFOUND ends the fetch loop once no more rows remain.' },
              ],
            },
            example: "IF emp_cur%ISOPEN THEN CLOSE emp_cur; END IF;",
          },
          {
            id: 'plsql-parameterized-cursor',
            code: "DECLARE\n  CURSOR emp_cur(p_dept NUMBER) IS\n    SELECT first_name FROM employees WHERE department_id = p_dept;\n  v_name employees.first_name%TYPE;\nBEGIN\n  OPEN emp_cur(20);\n  FETCH emp_cur INTO v_name;\n  CLOSE emp_cur;\nEND;\n/",
            note: "Parameterized cursors accept arguments passed at OPEN time, letting one cursor definition serve many queries. This is cleaner than embedding variables directly in the SELECT.",
            explanation: {
              heading: 'Cursors that take parameters',
              intro: 'A parameterized cursor declares formal arguments that are supplied when it is opened, so a single definition can drive many variations of the same query.',
              points: [
                { term: 'Formal parameters', detail: 'Parameters are listed after the cursor name in its declaration and used inside the query like local read-only values.' },
                { term: 'Values at OPEN', detail: 'You pass actual values in the OPEN statement, and each open can supply different arguments.' },
                { term: 'Reusability', detail: 'One parameterized cursor replaces several near-identical cursors that differ only by a filter value.' },
                { term: 'Cleaner scoping', detail: 'Parameters keep the varying values close to the OPEN rather than relying on outer variables buried in the query.' },
                { term: 'Default values', detail: 'A cursor parameter may declare a default so callers can omit it and fall back to that value.' },
              ],
            },
            example: "OPEN emp_cur(30);",
          },
        ],
        children: [],
      },
      {
        id: 'plsql-cursor-for-loops',
        title: 'Cursor FOR Loops',
        level: 2,
        slug: 'cursor-for-loops',
        concepts: [
          {
            id: 'plsql-cursor-for',
            code: "BEGIN\n  FOR rec IN (SELECT first_name, salary FROM employees WHERE department_id = 10) LOOP\n    DBMS_OUTPUT.PUT_LINE(rec.first_name || ': ' || rec.salary);\n  END LOOP;\nEND;\n/",
            note: "A cursor FOR loop implicitly opens, fetches, and closes the cursor and declares the loop record. It is the cleanest way to iterate a query result.",
            explanation: {
              heading: 'Implicit cursor iteration',
              intro: 'The cursor FOR loop is the most concise way to walk a query result because Oracle manages every cursor mechanic for you.',
              points: [
                { term: 'Automatic open and close', detail: 'The loop opens the cursor before the first pass and closes it when iteration finishes or an exception exits.' },
                { term: 'Implicit record', detail: 'The loop variable is declared for you as a record matching the cursor, with a field per selected column.' },
                { term: 'No manual fetch', detail: 'Each pass fetches the next row automatically, and the loop ends when the rows are exhausted.' },
                { term: 'Inline subquery', detail: 'You can loop directly over a parenthesized SELECT without first declaring a named cursor.' },
                { term: 'Less error prone', detail: 'Because there is no explicit OPEN, FETCH, or CLOSE, there is nothing to forget or leak.' },
              ],
            },
            example: "FOR r IN (SELECT * FROM dept) LOOP NULL; END LOOP;",
          },
          {
            id: 'plsql-cursor-attributes',
            code: "BEGIN\n  UPDATE employees SET salary = salary * 1.1 WHERE department_id = 10;\n  DBMS_OUTPUT.PUT_LINE('Rows updated: ' || SQL%ROWCOUNT);\nEND;\n/",
            note: "The implicit cursor SQL exposes attributes for the last DML statement: SQL%ROWCOUNT gives affected rows, SQL%FOUND is true if any row changed. Useful without declaring a cursor.",
            explanation: {
              heading: 'The implicit SQL cursor',
              intro: 'Every DML statement runs through an implicit cursor named SQL whose attributes describe the most recent operation.',
              points: [
                { term: 'SQL percent ROWCOUNT', detail: 'This attribute returns how many rows the last INSERT, UPDATE, or DELETE affected.' },
                { term: 'SQL percent FOUND', detail: 'This is TRUE when the last DML statement changed at least one row and FALSE when it changed none.' },
                { term: 'SQL percent NOTFOUND', detail: 'This is the inverse of percent-FOUND and is handy for detecting a statement that matched no rows.' },
                { term: 'No declaration needed', detail: 'The SQL cursor is always available, so you can inspect DML results without writing an explicit cursor.' },
                { term: 'Reflects the latest statement', detail: 'The attributes describe only the most recently executed DML, so read them right after the statement.' },
              ],
            },
            example: "IF SQL%NOTFOUND THEN DBMS_OUTPUT.PUT_LINE('nothing changed'); END IF;",
          },
        ],
        children: [],
      },
    ],
  },
  {
    id: 'plsql-procedures',
    title: 'Procedures',
    level: 1,
    slug: 'procedures',
    concepts: [],
    children: [
      {
        id: 'plsql-procedures-usage',
        title: 'Stored Procedures',
        level: 2,
        slug: 'procedures-usage',
        concepts: [
          {
            id: 'plsql-proc-basic',
            code: "CREATE OR REPLACE PROCEDURE raise_salary(\n  p_emp_id IN NUMBER,\n  p_pct    IN NUMBER\n) AS\nBEGIN\n  UPDATE employees SET salary = salary * (1 + p_pct/100)\n  WHERE employee_id = p_emp_id;\nEND raise_salary;\n/",
            note: "Procedures are named stored subprograms with IN, OUT, and IN OUT parameters. They perform actions but do not return a value directly.",
            explanation: {
              heading: 'Stored procedures overview',
              intro: 'A stored procedure is a named subprogram saved in the database that performs an action, optionally exchanging values through its parameters.',
              points: [
                { term: 'CREATE OR REPLACE', detail: 'This clause compiles the procedure into the database, replacing any prior version with the same name.' },
                { term: 'IN parameters', detail: 'An IN parameter passes a value into the procedure and is read-only inside the body, which is the default mode.' },
                { term: 'OUT and IN OUT', detail: 'OUT sends a value back to the caller while IN OUT both receives and returns a value.' },
                { term: 'Action not value', detail: 'Unlike a function, a procedure has no RETURN value and is called as a statement rather than in an expression.' },
                { term: 'Invocation', detail: 'You call a procedure with EXEC in a client tool or as a plain statement inside another PL-SQL block.' },
              ],
            },
            example: "EXEC raise_salary(100, 10);",
          },
          {
            id: 'plsql-proc-out-params',
            code: "CREATE OR REPLACE PROCEDURE get_stats(\n  p_dept   IN  NUMBER,\n  p_count  OUT NUMBER,\n  p_avg    OUT NUMBER\n) AS\nBEGIN\n  SELECT COUNT(*), AVG(salary) INTO p_count, p_avg\n  FROM employees WHERE department_id = p_dept;\nEND;\n/",
            note: "OUT parameters return values to the caller; IN OUT parameters pass a value in and hand a modified one back. Use named notation (p_dept => 10) for clarity with many parameters.",
            explanation: {
              heading: 'Returning data through parameters',
              intro: 'When a subprogram must return more than one value, OUT and IN OUT parameters carry results back to variables the caller supplies.',
              points: [
                { term: 'OUT semantics', detail: 'An OUT parameter starts as NULL inside the body and its final value is copied back to the caller variable.' },
                { term: 'IN OUT semantics', detail: 'An IN OUT parameter arrives with the caller value, can be modified, and the updated value is returned.' },
                { term: 'Multiple results', detail: 'Several OUT parameters let one procedure hand back many computed values at once, such as a count and an average.' },
                { term: 'Named notation', detail: 'Passing arguments as name arrow value makes long calls readable and lets you skip parameters that have defaults.' },
                { term: 'Actual must be a variable', detail: 'An argument bound to an OUT parameter must be a variable, not a literal, so it can receive the returned value.' },
              ],
            },
            example: "DECLARE n NUMBER; a NUMBER; BEGIN get_stats(10, n, a); END;\n/",
          },
        ],
        children: [],
      },
    ],
  },
  {
    id: 'plsql-functions',
    title: 'Functions',
    level: 1,
    slug: 'functions',
    concepts: [],
    children: [
      {
        id: 'plsql-functions-usage',
        title: 'Stored Functions',
        level: 2,
        slug: 'functions-usage',
        concepts: [
          {
            id: 'plsql-func-basic',
            code: "CREATE OR REPLACE FUNCTION get_annual_salary(\n  p_emp_id IN NUMBER\n) RETURN NUMBER AS\n  v_sal NUMBER;\nBEGIN\n  SELECT salary * 12 INTO v_sal FROM employees WHERE employee_id = p_emp_id;\n  RETURN v_sal;\nEND;\n/",
            note: "Functions return a single value via RETURN and can be called in SQL and PL/SQL expressions. Keep them side-effect free to use them in queries.",
            explanation: {
              heading: 'Stored functions overview',
              intro: 'A stored function computes and returns a single value, which lets you call it inside both PL-SQL and ordinary SQL expressions.',
              points: [
                { term: 'RETURN clause', detail: 'The header declares the return datatype and every path through the body must execute a RETURN statement.' },
                { term: 'Usable in SQL', detail: 'A function can appear in a SELECT list or WHERE clause, so you can test it against the DUAL table.' },
                { term: 'Avoid side effects', detail: 'A function used in queries should not perform DML or the database may reject or misorder its execution.' },
                { term: 'Single value', detail: 'A function returns exactly one value, whereas returning several results calls for a procedure with OUT parameters.' },
                { term: 'Expression friendly', detail: 'Because it returns a value, a function can be nested inside larger calculations and assignments.' },
              ],
            },
            example: "SELECT get_annual_salary(100) FROM dual;",
          },
          {
            id: 'plsql-deterministic-func',
            code: "CREATE OR REPLACE FUNCTION to_celsius(p_f NUMBER)\nRETURN NUMBER DETERMINISTIC AS\nBEGIN\n  RETURN (p_f - 32) * 5 / 9;\nEND;\n/",
            note: "Marking a function DETERMINISTIC promises the same input always yields the same output, letting Oracle cache results and use the function in function-based indexes and materialized views.",
            explanation: {
              heading: 'Deterministic functions',
              intro: 'The DETERMINISTIC keyword tells Oracle that a function always returns the same result for the same inputs, unlocking caching and indexing optimizations.',
              points: [
                { term: 'The promise', detail: 'You assert that the function output depends only on its arguments and never on session state, tables, or time.' },
                { term: 'Function-based indexes', detail: 'Only a deterministic function may be used in a function-based index because the stored values must stay valid.' },
                { term: 'Materialized views', detail: 'Deterministic functions can appear in materialized views whose contents are computed once and refreshed.' },
                { term: 'Result reuse', detail: 'Within a query Oracle may reuse a cached result instead of calling the function again for the same input.' },
                { term: 'Correctness risk', detail: 'Declaring a non-deterministic function as DETERMINISTIC can produce wrong or stale results, so use it honestly.' },
              ],
            },
            example: "CREATE INDEX idx_c ON readings(to_celsius(f_temp));",
          },
        ],
        children: [],
      },
    ],
  },
  {
    id: 'plsql-packages',
    title: 'Packages',
    level: 1,
    slug: 'packages',
    concepts: [],
    children: [
      {
        id: 'plsql-packages-usage',
        title: 'Specification and Body',
        level: 2,
        slug: 'packages-usage',
        concepts: [
          {
            id: 'plsql-pkg-spec',
            code: "CREATE OR REPLACE PACKAGE employee_pkg AS\n  PROCEDURE hire(p_name VARCHAR2, p_dept NUMBER);\n  FUNCTION get_salary(p_id NUMBER) RETURN NUMBER;\nEND employee_pkg;\n/",
            note: "A package groups related procedures, functions, types, and variables. The specification declares the public interface visible to callers.",
            explanation: {
              heading: 'The package specification',
              intro: 'A package specification is the public contract that lists the procedures, functions, types, and variables callers are allowed to use.',
              points: [
                { term: 'Public interface', detail: 'Anything declared in the spec is visible to other programs, forming the packages published API.' },
                { term: 'No implementation', detail: 'The spec only declares subprogram headers and shared items, while the actual code lives in the body.' },
                { term: 'Related grouping', detail: 'Packaging related routines together keeps a subject area, like employee handling, in one logical unit.' },
                { term: 'Compile independence', detail: 'Callers depend on the spec, so changing only the body does not force dependent code to recompile.' },
                { term: 'Dot qualified calls', detail: 'You invoke a packaged routine by prefixing it with the package name, such as package dot procedure.' },
              ],
            },
            example: "employee_pkg.hire('Ada', 10);",
          },
          {
            id: 'plsql-pkg-body',
            code: "CREATE OR REPLACE PACKAGE BODY employee_pkg AS\n  PROCEDURE hire(p_name VARCHAR2, p_dept NUMBER) IS\n  BEGIN\n    INSERT INTO employees (first_name, department_id) VALUES (p_name, p_dept);\n  END;\n  FUNCTION get_salary(p_id NUMBER) RETURN NUMBER IS\n    v NUMBER;\n  BEGIN\n    SELECT salary INTO v FROM employees WHERE employee_id = p_id;\n    RETURN v;\n  END;\nEND employee_pkg;\n/",
            note: "The package body implements the declared subprograms and may add private helpers. Package state (variables) persists for a session.",
            explanation: {
              heading: 'The package body',
              intro: 'The package body supplies the code behind every declared subprogram and can hold private helpers and state that outsiders never see.',
              points: [
                { term: 'Implements the spec', detail: 'Each subprogram declared in the specification must have a matching implementation in the body.' },
                { term: 'Private members', detail: 'Routines and variables defined only in the body are hidden from callers and support the public ones.' },
                { term: 'Session-persistent state', detail: 'Package variables keep their values for the whole session, acting like per-session global memory.' },
                { term: 'Optional initialization', detail: 'An initialization section at the end of the body runs once when the package is first referenced in a session.' },
                { term: 'Body-only recompile', detail: 'Because the spec stays fixed, editing the body alone avoids invalidating programs that depend on the package.' },
              ],
            },
            example: "v_pay := employee_pkg.get_salary(100);",
          },
          {
            id: 'plsql-pkg-constants',
            code: "CREATE OR REPLACE PACKAGE config_pkg AS\n  c_max_retries CONSTANT PLS_INTEGER := 3;\n  g_env VARCHAR2(10) := 'prod';\nEND config_pkg;\n/",
            note: "Package specs are a natural home for shared constants and global variables. Referenced as package.name, they give a single source of truth without a config table.",
            explanation: {
              heading: 'Package constants and globals',
              intro: 'Declaring constants and globals in a package specification centralizes configuration values so every program reads them from one place.',
              points: [
                { term: 'Single source of truth', detail: 'A constant like maximum retries lives in one spec instead of being duplicated across many programs.' },
                { term: 'PLS_INTEGER for counters', detail: 'Small whole-number constants often use PLS_INTEGER because it is faster than NUMBER for integer arithmetic.' },
                { term: 'Qualified reference', detail: 'Code reads a shared value as package dot name, making its origin explicit at the point of use.' },
                { term: 'Global variables', detail: 'A non-constant package variable holds session state that any program can read and update through the package.' },
                { term: 'No config table needed', detail: 'For static settings this avoids an extra lookup table while keeping values easy to find and change.' },
              ],
            },
            example: "IF v_tries > config_pkg.c_max_retries THEN NULL; END IF;",
          },
        ],
        children: [],
      },
    ],
  },
  {
    id: 'plsql-triggers',
    title: 'Triggers',
    level: 1,
    slug: 'triggers',
    concepts: [],
    children: [
      {
        id: 'plsql-triggers-usage',
        title: 'Row and Statement Triggers',
        level: 2,
        slug: 'triggers-usage',
        concepts: [
          {
            id: 'plsql-trigger-basic',
            code: "CREATE OR REPLACE TRIGGER trg_audit\nBEFORE UPDATE ON employees\nFOR EACH ROW\nBEGIN\n  :NEW.last_modified := SYSDATE;\nEND;\n/",
            note: "Triggers fire BEFORE/AFTER INSERT/UPDATE/DELETE. Row triggers (FOR EACH ROW) can read :OLD and :NEW pseudo-records; BEFORE row triggers can assign :NEW.",
            explanation: {
              heading: 'Trigger timing and records',
              intro: 'A trigger is code that fires automatically in response to a DML event, and its timing and level decide what it can see and change.',
              points: [
                { term: 'Timing point', detail: 'BEFORE triggers run before the row change is applied while AFTER triggers run once it has been applied.' },
                { term: 'Triggering events', detail: 'A trigger can respond to INSERT, UPDATE, or DELETE, and one trigger may cover several of these events.' },
                { term: 'FOR EACH ROW', detail: 'A row-level trigger fires once per affected row, whereas a statement trigger fires once for the whole statement.' },
                { term: 'OLD and NEW records', detail: 'In a row trigger colon-OLD holds the prior column values and colon-NEW holds the incoming ones.' },
                { term: 'Assigning NEW', detail: 'Only a BEFORE row trigger may assign to colon-NEW to modify the values that get written, such as stamping a date.' },
              ],
            },
            example: "CREATE TRIGGER t BEFORE INSERT ON t FOR EACH ROW BEGIN :NEW.id := seq.NEXTVAL; END;",
          },
          {
            id: 'plsql-trigger-when-of',
            code: "CREATE OR REPLACE TRIGGER trg_raise\nBEFORE UPDATE OF salary ON employees\nFOR EACH ROW\nWHEN (NEW.salary > OLD.salary * 1.5)\nBEGIN\n  RAISE_APPLICATION_ERROR(-20010, 'Raise too large');\nEND;\n/",
            note: "UPDATE OF column restricts the trigger to changes on specific columns, and the WHEN clause adds a row-level condition (using NEW/OLD without colons) so the body runs only when needed.",
            explanation: {
              heading: 'Narrowing when a trigger fires',
              intro: 'Oracle lets you scope a trigger tightly so it fires only for relevant column changes and only when a condition holds.',
              points: [
                { term: 'UPDATE OF columns', detail: 'Listing columns after UPDATE OF fires the trigger only when one of those columns is part of the update.' },
                { term: 'WHEN clause', detail: 'The WHEN clause adds a row-level condition, and the trigger body runs only for rows that satisfy it.' },
                { term: 'No colons in WHEN', detail: 'Inside WHEN you reference NEW and OLD without the leading colon, unlike in the trigger body.' },
                { term: 'Efficiency', detail: 'Filtering at the WHEN and UPDATE OF level avoids running body logic for rows that do not matter.' },
                { term: 'Raising errors', detail: 'A trigger can call RAISE_APPLICATION_ERROR to reject a change and roll back the offending statement.' },
              ],
            },
            example: "AFTER INSERT OR UPDATE OR DELETE ON t",
          },
        ],
        children: [],
      },
    ],
  },
  {
    id: 'plsql-exceptions',
    title: 'Exceptions',
    level: 1,
    slug: 'exceptions',
    concepts: [],
    children: [
      {
        id: 'plsql-exceptions-usage',
        title: 'Exception Handling',
        level: 2,
        slug: 'exceptions-usage',
        concepts: [
          {
            id: 'plsql-exception-basic',
            code: "DECLARE\n  e_custom EXCEPTION;\nBEGIN\n  IF v_qty < 0 THEN\n    RAISE e_custom;\n  END IF;\nEXCEPTION\n  WHEN NO_DATA_FOUND THEN DBMS_OUTPUT.PUT_LINE('none');\n  WHEN e_custom THEN DBMS_OUTPUT.PUT_LINE('bad qty');\n  WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLERRM);\nEND;\n/",
            note: "The EXCEPTION section handles errors by name. Predefined exceptions include NO_DATA_FOUND and TOO_MANY_ROWS; declare custom ones and RAISE them. OTHERS is the catch-all.",
            explanation: {
              heading: 'Handling exceptions by name',
              intro: 'The EXCEPTION section catches runtime errors through named handlers, letting a block respond to specific problems instead of failing abruptly.',
              points: [
                { term: 'Predefined exceptions', detail: 'Oracle names common errors such as NO_DATA_FOUND when a SELECT INTO finds nothing and TOO_MANY_ROWS when it finds several.' },
                { term: 'User-defined exceptions', detail: 'You can declare your own exception, RAISE it when a business rule is broken, and handle it by name.' },
                { term: 'The OTHERS handler', detail: 'A WHEN OTHERS branch catches any error not matched above and often reports SQLERRM for the message.' },
                { term: 'SQLERRM and SQLCODE', detail: 'Inside a handler SQLERRM returns the error text and SQLCODE returns the numeric error code.' },
                { term: 'Custom error numbers', detail: 'RAISE_APPLICATION_ERROR sends a chosen number between minus twenty thousand and minus twenty thousand nine ninety nine plus a message to the caller.' },
              ],
            },
            example: "RAISE_APPLICATION_ERROR(-20001, 'Invalid input');",
          },
          {
            id: 'plsql-pragma-exception-init',
            code: "DECLARE\n  e_fk_violation EXCEPTION;\n  PRAGMA EXCEPTION_INIT(e_fk_violation, -2291);\nBEGIN\n  INSERT INTO orders (customer_id) VALUES (-1);\nEXCEPTION\n  WHEN e_fk_violation THEN DBMS_OUTPUT.PUT_LINE('bad customer');\nEND;\n/",
            note: "PRAGMA EXCEPTION_INIT maps a named exception to an Oracle error number (like ORA-02291), so you can trap a specific server error by name instead of parsing SQLCODE in a WHEN OTHERS.",
            explanation: {
              heading: 'Naming server error codes',
              intro: 'PRAGMA EXCEPTION_INIT binds a user-declared exception to a specific Oracle error number so you can trap that server error cleanly by name.',
              points: [
                { term: 'The mapping', detail: 'The pragma links a declared exception to a negative ORA error number such as minus two thousand two hundred ninety one.' },
                { term: 'Named handling', detail: 'You can then write WHEN your exception instead of inspecting SQLCODE inside a WHEN OTHERS branch.' },
                { term: 'Common cases', detail: 'Typical targets include foreign key violations and unique constraint violations that map to well known error numbers.' },
                { term: 'Compile-time directive', detail: 'A pragma is an instruction to the compiler, placed in the declaration section right after the exception it names.' },
                { term: 'Readable intent', detail: 'A descriptive exception name makes the handler self-documenting compared to a bare numeric comparison.' },
              ],
            },
            example: "PRAGMA EXCEPTION_INIT(e_dup, -1);  -- unique violation",
          },
        ],
        children: [],
      },
    ],
  },
  {
    id: 'plsql-sequences',
    title: 'Sequences',
    level: 1,
    slug: 'sequences',
    concepts: [],
    children: [
      {
        id: 'plsql-sequences-usage',
        title: 'Generating Keys',
        level: 2,
        slug: 'sequences-usage',
        concepts: [
          {
            id: 'plsql-seq-basic',
            code: "CREATE SEQUENCE emp_seq START WITH 1000 INCREMENT BY 1 NOCACHE;\nINSERT INTO employees (employee_id, first_name)\nVALUES (emp_seq.NEXTVAL, 'Ada');\nSELECT emp_seq.CURRVAL FROM dual;",
            note: "Sequences generate unique numbers independent of tables. NEXTVAL advances and returns the next value; CURRVAL returns the last one used in the session.",
            explanation: {
              heading: 'Sequences for unique numbers',
              intro: 'A sequence is a standalone database object that hands out unique numbers, the classic way to generate surrogate primary keys in Oracle.',
              points: [
                { term: 'NEXTVAL', detail: 'Referencing NEXTVAL advances the sequence and returns the new value, and it is often selected against the DUAL table.' },
                { term: 'CURRVAL', detail: 'CURRVAL returns the value last produced by NEXTVAL in the current session and errors if NEXTVAL has not run yet.' },
                { term: 'Table independence', detail: 'A sequence is not tied to any table, so one sequence can feed several tables if desired.' },
                { term: 'Caching and gaps', detail: 'NOCACHE avoids caching but gaps can still appear from rollbacks, and NEXTVAL is never rolled back.' },
                { term: 'Configuration', detail: 'START WITH sets the first value and INCREMENT BY sets the step between successive numbers.' },
              ],
            },
            example: "SELECT emp_seq.NEXTVAL FROM dual;",
          },
          {
            id: 'plsql-identity-column',
            code: "CREATE TABLE orders (\n  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  total NUMBER\n);\nINSERT INTO orders (total) VALUES (99);",
            note: "Oracle 12c+ supports identity columns (GENERATED ALWAYS/BY DEFAULT AS IDENTITY), which manage a hidden sequence automatically, replacing the classic trigger-plus-sequence pattern.",
            explanation: {
              heading: 'Identity columns in 12c',
              intro: 'Starting with Oracle Database 12c an identity column auto-populates a numeric key from a sequence Oracle manages behind the scenes.',
              points: [
                { term: 'GENERATED ALWAYS', detail: 'With GENERATED ALWAYS Oracle always supplies the value and rejects any explicit insert into the column.' },
                { term: 'GENERATED BY DEFAULT', detail: 'With BY DEFAULT Oracle supplies a value only when the insert omits one, allowing manual overrides.' },
                { term: 'ON NULL variant', detail: 'Adding ON NULL makes Oracle generate a value even when the insert explicitly passes NULL for the column.' },
                { term: 'Hidden sequence', detail: 'The database creates and maintains an internal sequence, so no separate sequence object is needed.' },
                { term: 'Replaces old pattern', detail: 'Identity columns retire the older approach of a BEFORE INSERT trigger calling a sequence NEXTVAL.' },
              ],
            },
            example: "id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY",
          },
        ],
        children: [],
      },
    ],
  },
  {
    id: 'plsql-bulk-operations',
    title: 'Bulk Operations',
    level: 1,
    slug: 'bulk-operations',
    concepts: [],
    children: [
      {
        id: 'plsql-bulk-usage',
        title: 'BULK COLLECT and FORALL',
        level: 2,
        slug: 'bulk-usage',
        concepts: [
          {
            id: 'plsql-bulk-collect',
            code: "DECLARE\n  TYPE id_tab IS TABLE OF employees.employee_id%TYPE;\n  v_ids id_tab;\nBEGIN\n  SELECT employee_id BULK COLLECT INTO v_ids FROM employees;\n  FORALL i IN 1..v_ids.COUNT\n    UPDATE employees SET salary = salary * 1.05 WHERE employee_id = v_ids(i);\nEND;\n/",
            note: "BULK COLLECT fetches many rows into a collection in one context switch; FORALL sends batched DML to the SQL engine. Together they greatly reduce per-row overhead.",
            explanation: {
              heading: 'Bulk processing basics',
              intro: 'BULK COLLECT and FORALL cut the costly back and forth between the PL-SQL engine and the SQL engine by moving many rows at once.',
              points: [
                { term: 'Context switches', detail: 'Row-by-row processing pays a switch between the two engines each pass, and bulk operations collapse those switches.' },
                { term: 'BULK COLLECT INTO', detail: 'This clause loads all queried rows into one or more collections in a single fetch.' },
                { term: 'FORALL statement', detail: 'FORALL sends an entire array of bind values to the SQL engine as one batched DML operation.' },
                { term: 'Collection index range', detail: 'FORALL iterates over a collection index range such as first through last rather than executing a general loop body.' },
                { term: 'Performance gain', detail: 'For large sets these techniques often run dramatically faster than the equivalent single-row cursor loop.' },
              ],
            },
            example: "FORALL i IN v_ids.FIRST..v_ids.LAST DELETE FROM t WHERE id = v_ids(i);",
          },
          {
            id: 'plsql-bulk-limit',
            code: "DECLARE\n  CURSOR c IS SELECT * FROM big_table;\n  TYPE t IS TABLE OF c%ROWTYPE;\n  v_rows t;\nBEGIN\n  OPEN c;\n  LOOP\n    FETCH c BULK COLLECT INTO v_rows LIMIT 500;\n    EXIT WHEN v_rows.COUNT = 0;\n    -- process this batch\n  END LOOP;\n  CLOSE c;\nEND;\n/",
            note: "Fetching an unbounded result with BULK COLLECT can exhaust memory. The LIMIT clause fetches in fixed-size batches, balancing throughput against memory use for very large tables.",
            explanation: {
              heading: 'Batching with the LIMIT clause',
              intro: 'The LIMIT clause on BULK COLLECT caps how many rows come back per fetch so huge result sets do not overwhelm session memory.',
              points: [
                { term: 'Memory risk', detail: 'An unbounded BULK COLLECT loads every row into a collection at once, which can exhaust the process global area for big tables.' },
                { term: 'Fixed-size batches', detail: 'LIMIT with a count fetches that many rows each pass, keeping the working collection small.' },
                { term: 'Loop pattern', detail: 'You fetch in a loop and exit when the collection count is zero, meaning no rows remained.' },
                { term: 'Tuning the size', detail: 'A batch of a few hundred to a few thousand rows usually balances speed against memory.' },
                { term: 'Explicit cursor needed', detail: 'LIMIT works with an explicit cursor fetch rather than the single-statement SELECT BULK COLLECT form.' },
              ],
            },
            example: "FETCH c BULK COLLECT INTO v_rows LIMIT 1000;",
          },
        ],
        children: [],
      },
    ],
  },
  {
    id: 'plsql-collections',
    title: 'Records and Collections',
    level: 1,
    slug: 'collections',
    concepts: [],
    children: [
      {
        id: 'plsql-records',
        title: 'Records',
        level: 2,
        slug: 'records',
        concepts: [
          {
            id: 'plsql-record-basic',
            code: "DECLARE\n  TYPE emp_rec IS RECORD (\n    id   NUMBER,\n    name VARCHAR2(50)\n  );\n  v_emp emp_rec;\nBEGIN\n  v_emp.id := 1;\n  v_emp.name := 'Ada';\nEND;\n/",
            note: "A RECORD groups related fields into one composite variable, accessed with dot notation. Table-based records use %ROWTYPE instead of a manual definition.",
            explanation: {
              heading: 'Records as composite variables',
              intro: 'A record bundles several related fields into one variable so you can pass and manipulate a group of values as a unit.',
              points: [
                { term: 'TYPE definition', detail: 'You define a record type with TYPE name IS RECORD listing each field name and its datatype.' },
                { term: 'Dot access', detail: 'Individual fields are read and written with dot notation such as record dot field.' },
                { term: 'Anchored alternative', detail: 'For a record that mirrors a table row, percent-ROWTYPE is simpler than writing out every field by hand.' },
                { term: 'Whole-record assignment', detail: 'You can copy one record to another of the same type in a single assignment.' },
                { term: 'Nested composites', detail: 'A record field can itself be another record or a collection, letting you model richer structures.' },
              ],
            },
            example: "v_emp.name := 'Grace';",
          },
          {
            id: 'plsql-nested-varray',
            code: "DECLARE\n  TYPE num_list IS TABLE OF NUMBER;\n  v_nums num_list := num_list(10, 20, 30);\nBEGIN\n  v_nums.EXTEND;\n  v_nums(4) := 40;\n  DBMS_OUTPUT.PUT_LINE(v_nums.COUNT);\nEND;\n/",
            note: "Collections include associative arrays (index-by), nested tables (unbounded), and VARRAYs (bounded). Methods like COUNT, EXTEND, and DELETE manage them.",
            explanation: {
              heading: 'The three collection types',
              intro: 'PL-SQL offers three collection kinds that differ in bounds, storage, and how their indexes work.',
              points: [
                { term: 'Associative arrays', detail: 'These are in-memory key-value maps indexed by integers or strings and are sparse by nature.' },
                { term: 'Nested tables', detail: 'A nested table is an unbounded ordered collection that can be stored in a column and can become sparse after deletes.' },
                { term: 'VARRAYs', detail: 'A VARRAY has a fixed maximum size declared up front and always stores its elements densely in order.' },
                { term: 'EXTEND before assign', detail: 'Nested tables and VARRAYs must be extended with EXTEND to make room before assigning a new element.' },
                { term: 'Collection methods', detail: 'Methods like COUNT, FIRST, LAST, EXISTS, and DELETE inspect and manage the collections contents.' },
              ],
            },
            example: "TYPE grid IS VARRAY(10) OF NUMBER;",
          },
          {
            id: 'plsql-associative-array',
            code: "DECLARE\n  TYPE name_map IS TABLE OF NUMBER INDEX BY VARCHAR2(50);\n  v_salaries name_map;\nBEGIN\n  v_salaries('Ada') := 5000;\n  v_salaries('Grace') := 6000;\n  DBMS_OUTPUT.PUT_LINE(v_salaries('Ada'));\nEND;\n/",
            note: "Associative arrays (INDEX BY) are sparse, in-memory key-value maps indexed by integer or string keys. They are not stored in tables and are ideal for lookups and caching within a block.",
            explanation: {
              heading: 'Associative arrays as maps',
              intro: 'Associative arrays behave like hash maps in PL-SQL memory, mapping keys to values without any fixed size or table storage.',
              points: [
                { term: 'INDEX BY clause', detail: 'The type declares its key type with INDEX BY, commonly VARCHAR2 for string keys or PLS_INTEGER for numeric ones.' },
                { term: 'Sparse and unordered', detail: 'Keys need not be contiguous, so the array can hold scattered values addressed directly by key.' },
                { term: 'Memory only', detail: 'An associative array lives in session memory and cannot be stored in a database column.' },
                { term: 'EXISTS check', detail: 'Calling EXISTS with a key tests whether an element is present before you read it to avoid a missing-element error.' },
                { term: 'Fast lookups', detail: 'They are ideal for in-block caching and lookups, such as mapping a name to a salary.' },
              ],
            },
            example: "IF v_salaries.EXISTS('Ada') THEN NULL; END IF;",
          },
        ],
        children: [],
      },
    ],
  },
  {
    id: 'plsql-dynamic-sql',
    title: 'Dynamic SQL',
    level: 1,
    slug: 'dynamic-sql',
    concepts: [],
    children: [
      {
        id: 'plsql-dynamic-usage',
        title: 'EXECUTE IMMEDIATE',
        level: 2,
        slug: 'dynamic-usage',
        concepts: [
          {
            id: 'plsql-dynamic-basic',
            code: "DECLARE\n  v_count NUMBER;\nBEGIN\n  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM employees WHERE department_id = :d'\n    INTO v_count USING 10;\nEND;\n/",
            note: "EXECUTE IMMEDIATE runs SQL or PL/SQL built at runtime. Use USING for bind variables to prevent injection and enable plan reuse; INTO captures a single-row result.",
            explanation: {
              heading: 'Running SQL at runtime',
              intro: 'EXECUTE IMMEDIATE runs a statement whose text is assembled while the program runs, which is essential for DDL and flexible queries in PL-SQL.',
              points: [
                { term: 'Dynamic statements', detail: 'It executes SQL or PL-SQL held in a string, including DDL like CREATE TABLE that static PL-SQL cannot run directly.' },
                { term: 'USING for binds', detail: 'The USING clause supplies bind values for placeholders, which prevents SQL injection and lets Oracle reuse execution plans.' },
                { term: 'INTO for results', detail: 'The INTO clause captures a single-row query result into one or more variables.' },
                { term: 'Bind over concatenate', detail: 'Binding values is far safer than gluing user input into the statement text.' },
                { term: 'Placeholder naming', detail: 'Placeholders such as colon d are matched positionally to the values listed in USING.' },
              ],
            },
            example: "EXECUTE IMMEDIATE 'CREATE TABLE tmp (id NUMBER)';",
          },
          {
            id: 'plsql-dynamic-bulk',
            code: "DECLARE\n  TYPE t IS TABLE OF employees%ROWTYPE;\n  v_rows t;\nBEGIN\n  EXECUTE IMMEDIATE 'SELECT * FROM employees WHERE department_id = :d'\n    BULK COLLECT INTO v_rows USING 10;\nEND;\n/",
            note: "Dynamic SQL combines with BULK COLLECT INTO to fetch many rows at once from a runtime-built query, and with RETURNING ... INTO to capture values from dynamic DML.",
            explanation: {
              heading: 'Advanced dynamic SQL',
              intro: 'Dynamic SQL is not limited to single rows; it can bulk fetch many rows and capture values produced by dynamic DML.',
              points: [
                { term: 'Dynamic BULK COLLECT', detail: 'Combining EXECUTE IMMEDIATE with BULK COLLECT INTO loads many rows from a runtime-built query into a collection.' },
                { term: 'RETURNING INTO', detail: 'A dynamic INSERT, UPDATE, or DELETE can use RETURNING INTO to hand back affected column values.' },
                { term: 'OUT bind mode', detail: 'A USING argument can be marked OUT so a returned value flows back into the supplied variable.' },
                { term: 'Mixed bind modes', detail: 'One statement can bind some placeholders as inputs and others as outputs in the same USING list.' },
                { term: 'Fewer round trips', detail: 'Capturing results in the same dynamic statement avoids a separate query to read what changed.' },
              ],
            },
            example: "EXECUTE IMMEDIATE 'UPDATE t SET v=1 WHERE id=:1 RETURNING v INTO :2' USING v_id, OUT v_new;",
          },
        ],
        children: [],
      },
    ],
  },
  {
    id: 'plsql-ref-cursors',
    title: 'REF Cursors',
    level: 1,
    slug: 'ref-cursors',
    concepts: [],
    children: [
      {
        id: 'plsql-ref-cursor-usage',
        title: 'Cursor Variables',
        level: 2,
        slug: 'ref-cursor-usage',
        concepts: [
          {
            id: 'plsql-ref-cursor-basic',
            code: "CREATE OR REPLACE FUNCTION get_emps(p_dept NUMBER)\nRETURN SYS_REFCURSOR AS\n  v_cur SYS_REFCURSOR;\nBEGIN\n  OPEN v_cur FOR SELECT * FROM employees WHERE department_id = p_dept;\n  RETURN v_cur;\nEND;\n/",
            note: "REF cursors (SYS_REFCURSOR) are cursor variables that can be opened for a query and returned to a caller or client, decoupling the query from its consumer.",
            explanation: {
              heading: 'Cursor variables explained',
              intro: 'A REF cursor is a pointer to a query result that can be passed around, letting one program open a cursor and another consume it.',
              points: [
                { term: 'SYS_REFCURSOR type', detail: 'The built-in SYS_REFCURSOR is a weakly typed cursor variable that can point at any query.' },
                { term: 'OPEN FOR', detail: 'You associate a REF cursor with a query using OPEN cursor FOR, which can even be a dynamic string with USING binds.' },
                { term: 'Returnable results', detail: 'A function or procedure can return a REF cursor so the caller decides how to fetch the rows.' },
                { term: 'Decoupling', detail: 'Separating the query definition from its consumer lets the same result be handed to different callers.' },
                { term: 'Client friendly', detail: 'Application clients like Java and dot NET commonly receive REF cursors from stored procedures.' },
              ],
            },
            example: "OPEN v_cur FOR 'SELECT * FROM t WHERE id = :1' USING v_id;",
          },
          {
            id: 'plsql-ref-cursor-consume',
            code: "DECLARE\n  v_cur SYS_REFCURSOR;\n  v_emp employees%ROWTYPE;\nBEGIN\n  v_cur := get_emps(10);\n  LOOP\n    FETCH v_cur INTO v_emp;\n    EXIT WHEN v_cur%NOTFOUND;\n    DBMS_OUTPUT.PUT_LINE(v_emp.first_name);\n  END LOOP;\n  CLOSE v_cur;\nEND;\n/",
            note: "A caller fetches from a returned REF cursor just like an explicit cursor, then must CLOSE it. Client apps (JDBC, .NET) commonly consume REF cursors returned from stored procedures.",
            explanation: {
              heading: 'Consuming a REF cursor',
              intro: 'Once a program receives a REF cursor it fetches rows exactly as it would from an explicit cursor and is responsible for closing it.',
              points: [
                { term: 'Fetch loop', detail: 'The caller fetches rows into a variable or record until the cursor percent-NOTFOUND attribute signals the end.' },
                { term: 'Responsibility to close', detail: 'The consumer must CLOSE the REF cursor when done to release resources and avoid leaking open cursors.' },
                { term: 'Matching targets', detail: 'Fetch targets must match the columns the query returned, so a percent-ROWTYPE record is a convenient choice.' },
                { term: 'Cross-language use', detail: 'Clients written in Java or dot NET fetch the same result set returned by an Oracle stored procedure.' },
                { term: 'Same attributes', detail: 'A REF cursor exposes the familiar attributes like percent-FOUND and percent-ROWCOUNT during the fetch.' },
              ],
            },
            example: "FETCH v_cur INTO v_emp;",
          },
        ],
        children: [],
      },
    ],
  },
];

export default topics;
